# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

parameters:
    order_visitor_hierarchy:
        currency: 0
        order_product: 100
        product_total: 200
        shipping_method: 300
        payment_method: 400
        coupon: 500
        client_discount: 600
        client_group_discount: 700
        summary: 800
        order_confirmation: 900

well_commerce_api:
    request_handler:
        order:
            manager: order.manager
        order_status:
            manager: order_status.manager
        order_status_group:
            manager: order_status_group.manager
        payment:
            manager: payment.manager
        payment_method:
            manager: payment_method.manager
        shipping_method:
            manager: shipping_method.manager
    serialization:
        WellCommerce\Bundle\OrderBundle\Entity\Order:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/Order.yml"
        WellCommerce\Bundle\OrderBundle\Entity\OrderModifier:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/OrderModifier.yml"
        WellCommerce\Bundle\OrderBundle\Entity\OrderSummary:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/OrderSummary.yml"
        WellCommerce\Bundle\OrderBundle\Entity\OrderProduct:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/OrderProduct.yml"
        WellCommerce\Bundle\OrderBundle\Entity\OrderProductTotal:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/OrderProductTotal.yml"
        WellCommerce\Bundle\OrderBundle\Entity\OrderStatus:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/OrderStatus.yml"
        WellCommerce\Bundle\OrderBundle\Entity\OrderStatusHistory:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/OrderStatusHistory.yml"
        WellCommerce\Bundle\OrderBundle\Entity\OrderStatusTranslation:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/OrderStatusTranslation.yml"
        WellCommerce\Bundle\OrderBundle\Entity\OrderStatusGroup:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/OrderStatusGroup.yml"
        WellCommerce\Bundle\OrderBundle\Entity\OrderStatusGroupTranslation:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/OrderStatusGroupTranslation.yml"
        WellCommerce\Bundle\OrderBundle\Entity\Payment:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/Payment.yml"
        WellCommerce\Bundle\OrderBundle\Entity\PaymentMethod:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/PaymentMethod.yml"
        WellCommerce\Bundle\OrderBundle\Entity\PaymentMethodTranslation:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/PaymentMethodTranslation.yml"
        WellCommerce\Bundle\OrderBundle\Entity\ShippingMethod:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/ShippingMethod.yml"
        WellCommerce\Bundle\OrderBundle\Entity\ShippingMethodCost:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/ShippingMethodCost.yml"
        WellCommerce\Bundle\OrderBundle\Entity\ShippingMethodTranslation:
            mapping: "@WellCommerceOrderBundle/Resources/config/serialization/ShippingMethodTranslation.yml"

well_commerce_app:
    locale_copier:
        entities:
            WellCommerce\Bundle\OrderBundle\Entity\OrderStatusTranslation:
                properties:
                    - name
            WellCommerce\Bundle\OrderBundle\Entity\OrderStatusGroupTranslation:
                properties:
                    - name
            WellCommerce\Bundle\OrderBundle\Entity\PaymentMethodTranslation:
                properties:
                    - name
            WellCommerce\Bundle\OrderBundle\Entity\ShippingMethodTranslation:
                properties:
                    - name
