# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

well_commerce_api:
    request_handler:
        attribute:
            manager: attribute.manager
        attribute_group:
            manager: attribute_group.manager
        attribute_value:
            manager: attribute_value.manager
        availability:
            manager: availability.manager
        category:
            manager: category.manager
        deliverer:
            manager: deliverer.manager
        producer:
            manager: producer.manager
        product:
            manager: product.manager
        product_status:
            manager: product_status.manager
        unit:
            manager: unit.manager
    serialization:
        WellCommerce\Bundle\CatalogBundle\Entity\Attribute:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/Attribute.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\AttributeTranslation:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/AttributeTranslation.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\AttributeGroup:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/AttributeGroup.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\AttributeGroupTranslation:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/AttributeGroupTranslation.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\AttributeValue:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/AttributeValue.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\AttributeValueTranslation:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/AttributeValueTranslation.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\Availability:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/Availability.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\AvailabilityTranslation:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/AvailabilityTranslation.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\Category:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/Category.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\CategoryRoute:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/CategoryRoute.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\CategoryTranslation:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/CategoryTranslation.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\Deliverer:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/Deliverer.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\DelivererTranslation:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/DelivererTranslation.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\Producer:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/Producer.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\ProducerRoute:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/ProducerRoute.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\ProducerTranslation:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/ProducerTranslation.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\Product:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/Product.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\ProductDistinction:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/ProductDistinction.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\Variant:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/Variant.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\VariantOption:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/VariantOption.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\ProductPhoto:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/ProductPhoto.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\ProductRoute:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/ProductRoute.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\ProductTranslation:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/ProductTranslation.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\ProductStatus:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/ProductStatus.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\ProductStatusRoute:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/ProductStatusRoute.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\ProductStatusTranslation:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/ProductStatusTranslation.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\Unit:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/Unit.yml"
        WellCommerce\Bundle\CatalogBundle\Entity\UnitTranslation:
            mapping: "@WellCommerceCatalogBundle/Resources/config/serialization/UnitTranslation.yml"

well_commerce_routing:
    dynamic_routing:
        category:
            entity: WellCommerce\Bundle\CatalogBundle\Entity\CategoryRoute
            defaults:
                _controller: category.controller.front:indexAction
                limit: 12
                page: 1
                orderBy: hierarchy
                orderDir: asc
                priceFrom: 0
                priceTo: 9999
                view: grid
                producers: ~
                attributes: ~
                categories: ~
            requirements:
                limit: "\\d{1,10}"
                page: "\\d{1,10}"
                orderBy: "hierarchy|name|finalPrice"
                orderDir: "asc|desc"
                priceFrom: "\\d{1,10}"
                priceTo: "\\d{1,10}"
                view: "grid|list"
                producers: "[\\d+_]+"
                attributes: "[\\d+_]+"
                categories: "[\\d+_]+"
            pattern: "{page},{limit},{orderBy},{orderDir},{priceFrom},{priceTo},{view},{producers},{attributes},{categories}"
        producer:
            entity: WellCommerce\Bundle\CatalogBundle\Entity\ProducerRoute
            defaults:
                _controller: producer.controller.front:indexAction
                limit: 12
                page: 1
                orderBy: hierarchy
                orderDir: asc
                priceFrom: 0
                priceTo: 9999
                view: grid
                producers: ~
                attributes: ~
            requirements:
                limit: "\\d{1,10}"
                page: "\\d{1,10}"
                orderBy: "hierarchy|name|finalPrice"
                orderDir: "asc|desc"
                priceFrom: "\\d{1,10}"
                priceTo: "\\d{1,10}"
                view: "grid|list"
                producers: "[\\d+_]+"
                attributes: "[\\d+_]+"
            pattern: "{page},{limit},{orderBy},{orderDir},{priceFrom},{priceTo},{view},{producers},{attributes}"
        product:
            entity: WellCommerce\Bundle\CatalogBundle\Entity\ProductRoute
            defaults:
                _controller: product.controller.front:indexAction
        product_status:
            entity: WellCommerce\Bundle\CatalogBundle\Entity\ProductStatusRoute
            defaults:
                _controller: product_status.controller.front:indexAction
                limit: 10
                page: 1
                orderBy: hierarchy
                orderDir: asc
                priceFrom: 0
                priceTo: 9999
                view: grid
                producers: ~
                attributes: ~
            requirements:
                limit: "\\d{1,10}"
                page: "\\d{1,10}"
                orderBy: "hierarchy|name|finalPrice"
                orderDir: "asc|desc"
                priceFrom: "\\d{1,10}"
                priceTo: "\\d{1,10}"
                view: "grid|list"
                producers: "[\\d+_]+"
                attributes: "[\\d+_]+"
            pattern: "{page},{limit},{orderBy},{orderDir},{priceFrom},{priceTo},{view},{producers},{attributes}"

well_commerce_app:
    locale_copier:
        entities:
            WellCommerce\Bundle\CatalogBundle\Entity\AttributeTranslation:
                properties:
                    - name
            WellCommerce\Bundle\CatalogBundle\Entity\AttributeGroupTranslation:
                properties:
                    - name
            WellCommerce\Bundle\CatalogBundle\Entity\AttributeValueTranslation:
                properties:
                    - name
            WellCommerce\Bundle\CatalogBundle\Entity\AvailabilityTranslation:
                properties:
                    - name
            WellCommerce\Bundle\CatalogBundle\Entity\CategoryTranslation:
                properties:
                    - name
                    - slug
            WellCommerce\Bundle\CatalogBundle\Entity\DelivererTranslation:
                properties:
                    - name
            WellCommerce\Bundle\CatalogBundle\Entity\ProducerTranslation:
                properties:
                    - name
                    - slug
            WellCommerce\Bundle\CatalogBundle\Entity\ProductTranslation:
                properties:
                    - name
                    - slug
            WellCommerce\Bundle\CatalogBundle\Entity\ProductStatusTranslation:
                properties:
                    - name
                    - slug
            WellCommerce\Bundle\CatalogBundle\Entity\UnitTranslation:
                properties:
                    - name

well_commerce_catalog:
    filters:
        priceFrom:
            type: integer
            condition: WellCommerce\Component\DataSet\Conditions\Condition\Gte
            enabled: true
            column: finalPrice
        priceTo:
            type: integer
            condition: WellCommerce\Component\DataSet\Conditions\Condition\Lte
            enabled: true
            column: finalPrice
        attributes:
            type: array
            condition: WellCommerce\Component\DataSet\Conditions\Condition\In
            enabled: true
            column: variantOption
        producers:
            type: array
            condition: WellCommerce\Component\DataSet\Conditions\Condition\In
            enabled: true
            column: producerId
        categories:
            type: array
            condition: WellCommerce\Component\DataSet\Conditions\Condition\In
            enabled: true
            column: filteredCategory

well_commerce_search:
    search_engine:
        index:
            types:
                product:
                    class: WellCommerce\Bundle\CatalogBundle\Search\ProductType
                    mapping:
                        sku:
                            indexable: true
                            boost: 1
                            fuzziness: 2
                            value_expression: resource.getSku()
                        name:
                            indexable: true
                            boost: 1
                            fuzziness: 3
                            value_expression: resource.translate(locale).getName()
                        short_description:
                            indexable: true
                            boost: 0.5
                            fuzziness: 0
                            value_expression: resource.translate(locale).getShortDescription()
                        description:
                            indexable: true
                            boost: 0.5
                            fuzziness: 0
                            value_expression: resource.translate(locale).getDescription()
                        producer:
                            indexable: true
                            boost: 0.5
                            fuzziness: 2
                            value_expression: resource.getProducer().translate(locale).getName()
                        category:
                            indexable: true
                            boost: 0.5
                            fuzziness: 2
                            value_expression: resource.getCategories().first().translate(locale).getName()
