# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

_admin_contact:
    resource: "@WellCommerceCmsBundle/Resources/config/routing/contact/admin.yml"
    prefix: /admin/cms/contact

_front_contact:
    resource: "@WellCommerceCmsBundle/Resources/config/routing/contact/front.yml"
    prefix: /contact

_admin_news:
    resource: "@WellCommerceCmsBundle/Resources/config/routing/news/admin.yml"
    prefix: /admin/cms/news

_front_news:
    resource: "@WellCommerceCmsBundle/Resources/config/routing/news/front.yml"
    prefix: /news

_admin_page:
    resource: "@WellCommerceCmsBundle/Resources/config/routing/page/admin.yml"
    prefix: /admin/cms/page
