# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    showcase.layout_box.configurator:
        class: WellCommerce\Bundle\ShowcaseBundle\Configurator\ShowcaseBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    showcase.box.controller:
        class: WellCommerce\Bundle\ShowcaseBundle\Controller\Box\ShowcaseBoxController
        arguments: ['@product_status.manager']
        calls:
            - [setContainer, ['@service_container']]
