
services:
    client.controller.front:
        class: WellCommerce\Bundle\AppBundle\Controller\Front\ClientController
        arguments: ['@client.manager']
        calls:
            - [setContainer, ['@service_container']]

    client_order.controller.front:
        class: WellCommerce\Bundle\AppBundle\Controller\Front\ClientOrderController
        arguments: ['@client.manager']
        calls:
            - [setContainer, ['@service_container']]

    client_login.layout_box.controller:
        class: WellCommerce\Bundle\AppBundle\Controller\Box\ClientLoginBoxController
        arguments: ['@client.manager']
        calls:
            - [setContainer, ['@service_container']]

    client_login.layout_box.configurator:
        class: WellCommerce\Bundle\AppBundle\Configurator\ClientLoginBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    client_menu.layout_box.controller:
        class: WellCommerce\Bundle\AppBundle\Controller\Box\ClientMenuBoxController
        arguments: ['@client.manager']
        calls:
            - [setContainer, ['@service_container']]

    client_menu.layout_box.configurator:
        class: WellCommerce\Bundle\AppBundle\Configurator\ClientMenuBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    client_order.layout_box.controller:
        class: WellCommerce\Bundle\AppBundle\Controller\Box\ClientOrderBoxController
        arguments: ['@client.manager']
        calls:
            - [setContainer, ['@service_container']]

    client_order.configurator:
        class: WellCommerce\Bundle\AppBundle\Configurator\ClientOrderBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    client_settings.controller.front:
        class: WellCommerce\Bundle\AppBundle\Controller\Front\ClientSettingsController
        arguments: ['@client.manager']
        calls:
            - [setContainer, ['@service_container']]

    client_settings.controller.box:
        class: WellCommerce\Bundle\AppBundle\Controller\Box\ClientSettingsBoxController
        arguments: ['@client.manager', '@client_contact_details.form_builder.front']
        calls:
            - [setContainer, ['@service_container']]

    client_settings.configurator:
        class: WellCommerce\Bundle\AppBundle\Configurator\ClientSettingsBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    client_registration.layout_box.controller:
        class: WellCommerce\Bundle\AppBundle\Controller\Box\ClientRegistrationBoxController
        arguments: ['@client.manager', '@client_register.form_builder.front']
        calls:
            - [setContainer, ['@service_container']]

    client_registration.layout_box.configurator:
        class: WellCommerce\Bundle\AppBundle\Configurator\ClientRegistrationBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    client_forgot_password.controller.front:
        class: WellCommerce\Bundle\AppBundle\Controller\Front\ClientForgotPasswordController
        arguments: ['@client.manager']
        calls:
            - [setContainer, ['@service_container']]

    client_forgot_password.layout_box.controller:
        class: WellCommerce\Bundle\AppBundle\Controller\Box\ClientForgotPasswordBoxController
        arguments: ['@client.manager', '@client_reset_password.form_builder.front']
        calls:
            - [setContainer, ['@service_container']]

    client_forgot_password.layout_box.configurator:
        class: WellCommerce\Bundle\AppBundle\Configurator\ClientForgotPasswordBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    client_address_book.controller.front:
        class: WellCommerce\Bundle\AppBundle\Controller\Front\ClientAddressBookController
        arguments: ['@client.manager']
        calls:
            - [setContainer, ['@service_container']]

    client_address_book.layout_box.controller:
        class: WellCommerce\Bundle\AppBundle\Controller\Box\ClientAddressBookBoxController
        arguments: ['@client.manager', '@client_address_book.form_builder.front']
        calls:
            - [setContainer, ['@service_container']]

    client_address_book.layout_box.configurator:
        class: WellCommerce\Bundle\AppBundle\Configurator\ClientAddressBookBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    client.subscriber:
        class: WellCommerce\Bundle\AppBundle\EventListener\ClientSubscriber
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setContainer, ['@service_container']]

    twig.extension.client_address_formatter:
        class: WellCommerce\Bundle\AppBundle\Twig\Extension\ClientAddressFormatterExtension
        tags:
            - { name: twig.extension }

    client.failure.handler:
        class: WellCommerce\Bundle\AppBundle\Security\LoginFailureHandler
        arguments: ['@router', front.client.login]

    client.validator.unique_username:
        class: WellCommerce\Bundle\AppBundle\Validator\UniqueUsernameValidator
        tags:
            - { name: validator.constraint_validator, alias: client.validator.unique_username }
        arguments: ['@client.repository', '@router.helper']

    client.validator.valid_password:
        class: WellCommerce\Bundle\AppBundle\Validator\ClientPasswordValidator
        tags:
            - { name: validator.constraint_validator, alias: client.validator.valid_password }

    dataset.transformer.client_cart:
        class: WellCommerce\Bundle\AppBundle\DataSet\Transformer\ClientCartTransformer
        tags:
            - { name: dataset.transformer, alias: client_cart }
        arguments: ['@translator.helper', '@order.repository']

    twig.extension.quick_login:
        class: WellCommerce\Bundle\AppBundle\Twig\Extension\QuickLoginExtension
        arguments:
            - '@client_login.form_builder.front'
            - '@router.helper'
        tags:
            - { name: twig.extension }

    client_group_discount.datagrid.filter:
        class: WellCommerce\Bundle\AppBundle\DataGrid\ClientGroupFilter
        arguments: ["@client_group.repository"]
