# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    product_search.layout_box.configurator:
        class: WellCommerce\Bundle\CatalogBundle\Configurator\ProductSearchBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    product_search.dataset.front:
        class: WellCommerce\Bundle\CatalogBundle\DataSet\Front\ProductSearchDataSet
        tags:
            - { name: dataset }
        arguments: ['@product.repository','@dataset.manager','@event_dispatcher']
        configurator: ['@dataset.configurator', configure]
        calls:
            - [setContainer, ['@service_container']]

    product_search.controller.front:
        class: WellCommerce\Bundle\CatalogBundle\Controller\Front\ProductSearchController
        arguments: ['@product.manager']
        calls:
            - [setContainer, ['@service_container']]

    product_search.layout_box.controller:
        class: WellCommerce\Bundle\CatalogBundle\Controller\Box\ProductSearchBoxController
        arguments: ['@product.manager']
        calls:
            - [setContainer, ['@service_container']]
