# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

_admin_attribute:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/attribute/admin.yml"
    prefix: /admin/catalog/attribute

_admin_attribute_group:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/attribute_group/admin.yml"
    prefix: /admin/catalog/attribute/group

_admin_attribute_value:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/attribute_value/admin.yml"
    prefix: /admin/catalog/attribute/value

_admin_availability:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/availability/admin.yml"
    prefix: /admin/catalog/availability

_admin_category:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/category/admin.yml"
    prefix: /admin/catalog/category

_admin_deliverer:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/deliverer/admin.yml"
    prefix: /admin/catalog/deliverer

_front_layered_navigation:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/layered_navigation/front.yml"
    prefix: /filter

_admin_producer:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/producer/admin.yml"
    prefix: /admin/catalog/producer

_admin_product:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/product/admin.yml"
    prefix: /admin/catalog/product

_front_product:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/product/front.yml"
    prefix: /product

_admin_product_status:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/product_status/admin.yml"
    prefix: /admin/catalog/product/status

_front_search:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/search/front.yml"
    prefix: /search

_admin_unit:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/unit/admin.yml"
    prefix: /admin/catalog/unit
