# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.user_group.index:
    path: /admin/user/group/index
    defaults:
        _controller: 'user_group.controller.admin:indexAction'
    options:
        require_admin_permission: user_group.index

admin.user_group.grid:
    path: /admin/user/group/grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'user_group.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: user_group.index

admin.user_group.add:
    path: /admin/user/group/add
    defaults:
        _controller: 'user_group.controller.admin:addAction'
    options:
        require_admin_permission: user_group.add

admin.user_group.edit:
    path: '/admin/user/group/edit/{id}'
    defaults:
        _controller: 'user_group.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: user_group.edit

admin.user_group.delete:
    path: '/admin/user/group/delete/{id}'
    defaults:
        _controller: 'user_group.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: user_group.delete

admin.user_group.delete_group:
    path: '/admin/user/group/delete_group'
    defaults:
        _controller: 'user_group.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: user_group.delete
