# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.producer.index:
    path: /index
    defaults:
        _controller: 'producer.controller.admin:indexAction'
    options:
        require_admin_permission: producer.index

admin.producer.grid:
    path: /grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'producer.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: producer.index

admin.producer.add:
    path: /add
    defaults:
        _controller: 'producer.controller.admin:addAction'
    options:
        require_admin_permission: producer.add

admin.producer.edit:
    path: '/edit/{id}'
    defaults:
        _controller: 'producer.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: producer.edit

admin.producer.delete:
    path: '/delete/{id}'
    defaults:
        _controller: 'producer.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: producer.delete

admin.producer.delete_group:
    path: '/delete_group'
    defaults:
        _controller: 'producer.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: producer.delete
