# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.routing.generate:
    path: /routing/generate
    defaults:
        _controller: 'route.controller.admin:generateAction'
    options:
        expose: true
        require_admin_permission: routing.index

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
