# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\CatalogBundle\Entity\Category:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: category
    repositoryClass: WellCommerce\Bundle\CatalogBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        productsCount:
            type: integer
            nullable: false
            options:
                default: 0
            column: products_count
        childrenCount:
            type: integer
            nullable: false
            options:
                default: 0
            column: children_count
        symbol:
            type: string
            nullable: false
            options:
                default: ''
    manyToOne:
        parent:
            targetEntity: WellCommerce\Bundle\CatalogBundle\Entity\Category
            fetch: LAZY
            inversedBy: children
            joinColumns:
                parent_id:
                    referencedColumnName: id
                    onDelete: CASCADE
    oneToMany:
        children:
            targetEntity: WellCommerce\Bundle\CatalogBundle\Entity\Category
            fetch: EXTRA_LAZY
            mappedBy: parent
    manyToMany:
        products:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Product
            fetch: EXTRA_LAZY
            mappedBy: categories
