WellCommerce\Bundle\NewsBundle\Entity\News:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: news
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        publish:
            type: boolean
            nullable: false
            options:
                default: true
        startDate:
            type: datetime
            nullable: true
        endDate:
            type: datetime
            nullable: true
        featured:
            type: boolean
            nullable: false
            options:
                default: false
    manyToOne:
        photo:
            targetEntity: WellCommerce\Bundle\MediaBundle\Entity\Media
            fetch: LAZY
            joinColumns:
                photo_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
    manyToMany:
        shops:
            targetEntity: WellCommerce\Bundle\ShopBundle\Entity\ShopInterface
            fetch: LAZY
            joinTable:
                name: shop_news
                joinColumns:
                    -
                        name: news_id
                        nullable: true
                        onDelete: CASCADE
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: shop_id
                        nullable: true
                        onDelete: CASCADE
                        referencedColumnName: id