# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

well_commerce_core:
    request_handler:
        contact:
            manager: contact.manager
        news:
            manager: news.manager
        page:
            manager: page.manager
    serialization:
        WellCommerce\Bundle\CmsBundle\Entity\Contact:
            mapping: "@WellCommerceCmsBundle/Resources/config/serialization/Contact.yml"
        WellCommerce\Bundle\CmsBundle\Entity\ContactTranslation:
            mapping: "@WellCommerceCmsBundle/Resources/config/serialization/ContactTranslation.yml"
        WellCommerce\Bundle\CmsBundle\Entity\ContactTicket:
            mapping: "@WellCommerceCmsBundle/Resources/config/serialization/ContactTicket.yml"
        WellCommerce\Bundle\CmsBundle\Entity\News:
            mapping: "@WellCommerceCmsBundle/Resources/config/serialization/News.yml"
        WellCommerce\Bundle\CmsBundle\Entity\NewsTranslation:
            mapping: "@WellCommerceCmsBundle/Resources/config/serialization/NewsTranslation.yml"
        WellCommerce\Bundle\CmsBundle\Entity\Page:
            mapping: "@WellCommerceCmsBundle/Resources/config/serialization/Page.yml"
        WellCommerce\Bundle\CmsBundle\Entity\PageRoute:
            mapping: "@WellCommerceCmsBundle/Resources/config/serialization/PageRoute.yml"
        WellCommerce\Bundle\CmsBundle\Entity\PageTranslation:
            mapping: "@WellCommerceCmsBundle/Resources/config/serialization/PageTranslation.yml"
    dynamic_routing:
        news:
            entity: WellCommerce\Bundle\CmsBundle\Entity\NewsRoute
            defaults:
                _controller: news.controller.front:viewAction
        page:
            entity: WellCommerce\Bundle\CmsBundle\Entity\PageRoute
            defaults:
                _controller: page.controller.front:indexAction

well_commerce_app:
    locale_copier:
        entities:
            WellCommerce\Bundle\CmsBundle\Entity\ContactTranslation:
                properties:
                    - name
            WellCommerce\Bundle\CmsBundle\Entity\NewsTranslation:
                properties:
                    - topic
                    - slug
            WellCommerce\Bundle\CmsBundle\Entity\PageTranslation:
                properties:
                    - name
                    - slug
