# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

front.contact.index:
    path: /
    options:
        breadcrumb:
            label: contact_ticket.index.contact
    defaults:
        _controller: 'contact.controller.front:indexAction'
